### ISSUE TITLE
Move spglsl in peerDependencies

### ISSUE THREAD

**Issue by SalvatorePreviti** [rottencandy/esbuild-plugin-spglsl#1]
I would suggest to move the dependency "spglsl" in peerDependencies, so the user will decide with version they wanna use and they are not bound to the version specified in your package.json

`peerDependencies: { spglsl: ">=0.2.6" }` or something like this.

peerDependencies will automatically install if using npm >= 7 in any case, and will raise a warning in npm6 if not installed, and will allow the user to select a different version if needed.

**Comment by rottencandy** [comment]
Thanks, fixed in 7e1312385a80bea2225a019b8842c36804dfee0d
